package render

import (
	"strings"
	"testing"

	"github.com/cruzambrociogl/archdoc/internal/archdoc"
)

func meta() Meta {
	return Meta{Tool: "test", Commit: "abc123", Source: "docker-compose.yml"}
}

// arc42 is twelve sections in a fixed order. Emitting eleven, or emitting them in a different
// order between runs, means it is not arc42.
func TestTwelveSectionsInOrder(t *testing.T) {
	s := Sections()

	if len(s) != 12 {
		t.Fatalf("got %d sections, want 12", len(s))
	}
	for i, sec := range s {
		if sec.Number != i+1 {
			t.Errorf("section %d is numbered %d", i+1, sec.Number)
		}
	}
}

// Five generated, seven human. That split is not a scoping convenience — it is why the
// regeneration boundary exists at all, and claiming to generate twelve would mean generating
// seven of them from nothing.
func TestOnlyFactBackedSectionsAreGenerated(t *testing.T) {
	files := Arc42(fixture(), meta())

	if len(files) != 5 {
		t.Fatalf("generated %d sections, want 5: %v", len(files), files)
	}

	for _, s := range Sections() {
		_, generated := files[s.File()]
		if generated != (s.Owner == Generated) {
			t.Errorf("section %d (%s): generated=%v, owner says otherwise", s.Number, s.Title, generated)
		}
		// The suffix is the mechanism, not decoration: it tells a person reading a directory
		// listing which files they may edit.
		if strings.HasSuffix(s.File(), ".generated.md") != (s.Owner == Generated) {
			t.Errorf("section %d file name %q does not match its owner", s.Number, s.File())
		}
	}
}

// OUT-04. A generated file has to say which version of what produced it, or a reader comparing
// two checkouts cannot tell which is stale.
func TestGeneratedFilesCarryTheStamp(t *testing.T) {
	for name, content := range Arc42(fixture(), meta()) {
		for _, want := range []string{"Generated by archdoc", "commit: abc123", "source: docker-compose.yml"} {
			if !strings.Contains(content, want) {
				t.Errorf("%s is missing %q", name, want)
			}
		}
	}
}

// A stub full of generic advice gets deleted unread. OUT-08 asks for questions derived from
// *this* model, and the test for that is that the model's own element names appear in them.
func TestStubsAskAboutThisSystem(t *testing.T) {
	stubs := Stubs(fixture(), meta())

	if len(stubs) != 7 {
		t.Fatalf("got %d stubs, want 7", len(stubs))
	}

	risks := stubs["11-risks-and-technical-debt.md"]
	if !strings.Contains(risks, "s3.amazonaws.com") {
		t.Errorf("the risks stub does not name the external system this model depends on:\n%s", risks)
	}

	strategy := stubs["04-solution-strategy.md"]
	if !strings.Contains(strategy, "container(s)") {
		t.Errorf("the strategy stub does not mention the decomposition:\n%s", strategy)
	}

	// Every stub must say plainly that it will not be touched again.
	for name, s := range stubs {
		if !strings.Contains(s, "never read or") {
			t.Errorf("%s does not tell the reader it is theirs", name)
		}
	}
}

// A runtime view describes behaviour, and configuration declares structure. Saying so is more
// useful than an invented sequence diagram — and it is what OUT-01 means by stubbing with an
// explicit note of what is missing.
func TestRuntimeViewSaysWhatItCannotKnow(t *testing.T) {
	out := Arc42(fixture(), meta())["06-runtime-view.generated.md"]

	if !strings.Contains(out, "cannot fill this section") {
		t.Errorf("the runtime view does not admit what it lacks:\n%s", out)
	}
	if strings.Contains(out, "sequenceDiagram") {
		t.Error("the runtime view invented a sequence")
	}
}

// Compose is a deployment description, so this section is shallow and real rather than empty.
func TestDeploymentViewReportsReachability(t *testing.T) {
	out := Arc42(fixture(), meta())["07-deployment-view.generated.md"]

	if !strings.Contains(out, "| Container | Reachable from outside | Networks |") {
		t.Fatalf("no reachability table:\n%s", out)
	}
	// api is the only container an actor reaches directly in the fixture.
	if !strings.Contains(out, "| api | yes |") {
		t.Error("the container an actor reaches is not marked reachable")
	}
	if !strings.Contains(out, "| db | no |") {
		t.Error("a container nothing outside reaches is marked reachable")
	}
}

// The index links every section and says who owns it.
//
// It deliberately does *not* say whether a section has been written yet. That changes the moment
// the same run creates the stub, so an index reporting it would differ between two otherwise
// identical runs — and a committed file that churns is one nobody trusts in a diff. Run-specific
// news goes to the terminal.
func TestIndexLinksEverySectionAndNamesItsOwner(t *testing.T) {
	out := Index(fixture(), meta())

	for _, s := range Sections() {
		if !strings.Contains(out, "]("+s.File()+")") {
			t.Errorf("section %d is not linked", s.Number)
		}
	}
	if !strings.Contains(out, "| 1 | [Introduction and Goals](01-introduction-and-goals.md) | you | never read or written |") {
		t.Error("a human section is not marked as untouched by archdoc")
	}
	if !strings.Contains(out, "| 3 | [Context and Scope](03-context-and-scope.generated.md) | archdoc | overwritten every run |") {
		t.Error("a generated section is not marked as overwritten")
	}
}

// The index is committed, so two identical runs must produce the same bytes.
func TestIndexIsStableAcrossRuns(t *testing.T) {
	first := Index(fixture(), meta())
	for range 5 {
		if Index(fixture(), meta()) != first {
			t.Fatal("the index differs between runs")
		}
	}
}

func TestArc42IsDeterministic(t *testing.T) {
	first := Arc42(fixture(), meta())["05-building-block-view.generated.md"] +
		Stubs(fixture(), meta())["11-risks-and-technical-debt.md"]

	for range 10 {
		got := Arc42(fixture(), meta())["05-building-block-view.generated.md"] +
			Stubs(fixture(), meta())["11-risks-and-technical-debt.md"]
		if got != first {
			t.Fatal("arc42 output differs between runs")
		}
	}
}

// One inbound edge is not a single point of failure, and saying so about everything would make
// the section noise. The hint fires only when something is genuinely central.
func TestRisksStubNamesTheMostDependedOnContainer(t *testing.T) {
	m := fixture()
	m.Nodes = append(m.Nodes, archdoc.Node{
		ID: "svc:worker", Name: "worker", Kind: archdoc.Application,
		Evidence: archdoc.Declared, Prov: at(30),
	})
	m.Edges = append(m.Edges, archdoc.Edge{
		From: "svc:worker", To: "svc:db", Label: "connects to",
		Traffic: true, Prov: []archdoc.Provenance{at(31)},
	})

	if out := Stubs(m.Normalise(), meta())["11-risks-and-technical-debt.md"]; !strings.Contains(out, "**db**") {
		t.Errorf("the most depended-on container is not raised:\n%s", out)
	}

	// And with only one inbound edge it stays quiet.
	if out := Stubs(fixture(), meta())["11-risks-and-technical-debt.md"]; strings.Contains(out, "**db**") {
		t.Error("a container with one inbound edge was called a single point of failure")
	}
}

// Immich's machine-learning service is the standing example: it appears in the model with no
// relationships, because every caller builds its URL at runtime.
func TestRisksStubNoticesAnUnconnectedContainer(t *testing.T) {
	m := fixture()
	m.Nodes = append(m.Nodes, archdoc.Node{
		ID: "svc:worker", Name: "worker", Kind: archdoc.Application,
		Evidence: archdoc.Declared, Prov: at(40),
	})

	out := Stubs(m.Normalise(), meta())["11-risks-and-technical-debt.md"]
	if !strings.Contains(out, "worker") {
		t.Errorf("an unconnected container is not raised as a risk:\n%s", out)
	}
}
