package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/cruzambrociogl/archdoc/internal/archdoc"
)

// arc42 is twelve sections in a fixed order. Roughly five can be filled from facts and seven
// need a person who knows *why* — and that split is the whole reason the regeneration boundary
// exists. Claiming to generate twelve would mean generating seven of them from nothing.
//
// Partial output is the honest output (§8). A section archdoc cannot fill is created once, with
// questions derived from this specific model rather than a generic placeholder, and then never
// touched again.

// Owner says who writes a section.
type Owner int

const (
	// Generated sections are tool-owned: overwritten in full on every run.
	Generated Owner = iota
	// Human sections are written once as a stub and never read or written again. A
	// documentation generator that eats someone's writing gets uninstalled once.
	Human
)

// Section is one arc42 chapter.
type Section struct {
	Number int
	Title  string
	Slug   string
	Owner  Owner
}

// File is where a section lands. The `.generated.md` suffix is not decoration: it is the
// mechanism that makes the boundary visible to a person looking at a directory listing, and the
// thing that tells the next run what it may overwrite.
func (s Section) File() string {
	if s.Owner == Generated {
		return fmt.Sprintf("%02d-%s.generated.md", s.Number, s.Slug)
	}
	return fmt.Sprintf("%02d-%s.md", s.Number, s.Slug)
}

// Sections is arc42's fixed order, with the ownership split from §14.
func Sections() []Section {
	return []Section{
		{1, "Introduction and Goals", "introduction-and-goals", Human},
		{2, "Architecture Constraints", "architecture-constraints", Human},
		{3, "Context and Scope", "context-and-scope", Generated},
		{4, "Solution Strategy", "solution-strategy", Human},
		{5, "Building Block View", "building-block-view", Generated},
		{6, "Runtime View", "runtime-view", Generated},
		{7, "Deployment View", "deployment-view", Generated},
		{8, "Cross-cutting Concepts", "cross-cutting-concepts", Human},
		{9, "Architecture Decisions", "architecture-decisions", Human},
		{10, "Quality Requirements", "quality-requirements", Human},
		{11, "Risks and Technical Debt", "risks-and-technical-debt", Human},
		{12, "Glossary", "glossary", Generated},
	}
}

// Meta is what OUT-04 stamps on every generated file: enough for a reader to know which version
// of which repository produced it, and what was applied on top.
type Meta struct {
	Tool   string // archdoc build
	Commit string // the scanned repository's commit, when it has one
	Source string // the configuration file the model came from
	Rules  []string

	// Pictures is true when context.svg and container.svg are being written beside the
	// markdown. The documents then show the drawn diagram and keep the Mermaid source in a
	// collapsed block; without pictures they show Mermaid, which needs no layout engine.
	Pictures bool
}

func (m Meta) stamp() string {
	var b strings.Builder

	b.WriteString("<!-- Generated by archdoc. Do not edit: this file is overwritten in full on\n")
	b.WriteString("     every run. Corrections belong in rules.yaml, which survives regeneration.\n")
	fmt.Fprintf(&b, "     tool:   %s\n", dash(m.Tool))
	fmt.Fprintf(&b, "     commit: %s\n", dash(m.Commit))
	fmt.Fprintf(&b, "     source: %s\n", dash(m.Source))
	if len(m.Rules) > 0 {
		fmt.Fprintf(&b, "     rules:  %s\n", strings.Join(m.Rules, ", "))
	}
	b.WriteString("-->\n\n")

	return b.String()
}

// Arc42 renders every section archdoc can fill from facts. The map is keyed on file name,
// relative to the documentation directory.
func Arc42(m archdoc.Model, meta Meta) map[string]string {
	out := map[string]string{}

	for _, s := range Sections() {
		if s.Owner != Generated {
			continue
		}

		var b strings.Builder
		fmt.Fprintf(&b, "# %d. %s\n\n", s.Number, s.Title)
		b.WriteString(meta.stamp())

		switch s.Number {
		case 3:
			b.WriteString(contextSection(m, meta))
		case 5:
			b.WriteString(buildingBlockSection(m, meta))
		case 6:
			b.WriteString(runtimeSection(m))
		case 7:
			b.WriteString(deploymentSection(m))
		case 12:
			b.WriteString(glossarySection(m))
		}

		out[s.File()] = b.String()
	}

	return out
}

func contextSection(m archdoc.Model, meta Meta) string {
	view := m.Context()

	var b strings.Builder
	b.WriteString("The system as a whole, and what surrounds it. Everything the repository declares is\n")
	b.WriteString("inside one box; everything it only references sits outside.\n\n")
	b.WriteString(figure(meta, "System context", "context.svg", Mermaid(view, false)))
	b.WriteString("\n")
	b.WriteString(elementTable(view))

	outside := 0
	for _, n := range view.Nodes {
		if n.Kind == archdoc.External {
			outside++
		}
	}
	if outside == 0 {
		b.WriteString("\nThe repository references no system it does not also declare. That is a finding\n")
		b.WriteString("about this repository, not a gap in the tool: where a system's external\n")
		b.WriteString("dependencies are configured at deploy time, the repository never names them.\n")
	}

	return b.String()
}

func buildingBlockSection(m archdoc.Model, meta Meta) string {
	view := m.Container()

	var b strings.Builder
	b.WriteString("The separately deployable pieces inside the system, and what talks to what.\n\n")
	b.WriteString(figure(meta, "Containers", "container.svg", Mermaid(view, true)))
	b.WriteString("\n")
	b.WriteString(elementTable(view))
	b.WriteString("\n")
	b.WriteString(relationshipTable(view))
	b.WriteString(networkTable(m, view))
	b.WriteString(excluded(m, view))

	return b.String()
}

// runtimeSection is generated and empty on purpose.
//
// A runtime view describes how a feature behaves *while running*. Configuration declares
// structure, never behaviour, so there is nothing here to read. Saying so — and naming the
// evidence that would be needed — is more useful than an invented sequence diagram, and it is
// what OUT-01 means by stubbing with an explicit note.
func runtimeSection(m archdoc.Model) string {
	var b strings.Builder

	b.WriteString("**archdoc cannot fill this section from configuration.**\n\n")
	b.WriteString("A runtime view describes how a feature behaves while running — the order of calls\n")
	b.WriteString("in a scenario, what happens on failure, where work is queued. Configuration\n")
	b.WriteString("declares *structure*: what exists, and what may reach what. It says nothing about\n")
	b.WriteString("sequence, and archdoc does not guess.\n\n")
	b.WriteString("Filling it would need one of:\n\n")
	b.WriteString("- **Static analysis of application source** — call graphs within and between services\n")
	b.WriteString("- **Runtime traces** — OpenTelemetry spans, or logs correlated by request\n")
	b.WriteString("- **A person**, writing the scenarios that matter\n\n")

	if edges := len(m.Container().Edges); edges > 0 {
		fmt.Fprintf(&b, "The %d relationship(s) in section 5 are the structural skeleton such a\n", edges)
		b.WriteString("scenario would move along. They say what *can* happen, not what does.\n")
	}

	return b.String()
}

// deploymentSection is shallow by nature and useful anyway.
//
// Compose describes a single host running containers, so the mapping is one level deep — a real
// deployment view arrives with orchestrator manifests, which are out of R1 scope. What it can
// say honestly is which containers are published to the outside and which networks they sit on,
// both of which are declared facts.
func deploymentSection(m archdoc.Model) string {
	var b strings.Builder

	b.WriteString("Compose describes one host running containers, so this view is one level deep.\n")
	b.WriteString("A layered deployment view needs orchestrator manifests, which are out of scope for\n")
	b.WriteString("this release.\n\n")
	b.WriteString("What the configuration does state is which containers are reachable from outside\n")
	b.WriteString("the host, and which networks each sits on.\n\n")

	view := m.Container()

	reachable := map[string]bool{}
	for _, e := range view.Edges {
		if from, ok := view.Node(e.From); ok && from.Kind == archdoc.Actor {
			reachable[e.To] = true
		}
	}

	b.WriteString("| Container | Reachable from outside | Networks |\n|---|---|---|\n")
	for _, n := range view.Nodes {
		if !n.Kind.Container() {
			continue
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n",
			n.Name, yesNo(reachable[n.ID]), dash(strings.Join(n.Networks, ", ")))
	}

	b.WriteString(networkTable(m, view))

	return b.String()
}

func glossarySection(m archdoc.Model) string {
	var b strings.Builder

	b.WriteString("Every element the model contains, with what it is and where it is declared.\n")
	b.WriteString("Terms only a person can define belong in section 8.\n\n")
	b.WriteString("| Term | Meaning | Declared at |\n|---|---|---|\n")

	nodes := append([]archdoc.Node(nil), m.Nodes...)
	sort.Slice(nodes, func(i, j int) bool { return nodes[i].Name < nodes[j].Name })

	for _, n := range nodes {
		meaning := typeName(n.Kind)
		if n.Technology != "" {
			meaning += ", " + n.Technology
		}
		if n.Description != "" {
			meaning += " — " + n.Description
		}
		fmt.Fprintf(&b, "| %s | %s | `%s` |\n", n.Name, meaning, n.Prov)
	}

	return b.String()
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}
