package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/cruzambrociogl/archdoc/internal/archdoc"
)

// arc42 is twelve sections in a fixed order. Roughly five can be filled from facts and seven
// need a person who knows *why* — and that split is the whole reason the regeneration boundary
// exists. Claiming to generate twelve would mean generating seven of them from nothing.
//
// Partial output is the honest output (§8). A section archdoc cannot fill is created once, with
// questions derived from this specific model rather than a generic placeholder, and then never
// touched again.

// Owner says who writes a section.
type Owner int

const (
	// Generated sections are tool-owned: overwritten in full on every run.
	Generated Owner = iota
	// Human sections are written once as a stub and never read or written again. A
	// documentation generator that eats someone's writing gets uninstalled once.
	Human
)

// Section is one arc42 chapter.
type Section struct {
	Number int
	Title  string
	Slug   string
	Owner  Owner
}

// File is where a section lands. The `.generated.md` suffix is not decoration: it is the
// mechanism that makes the boundary visible to a person looking at a directory listing, and the
// thing that tells the next run what it may overwrite.
func (s Section) File() string {
	if s.Owner == Generated {
		return fmt.Sprintf("%02d-%s.generated.md", s.Number, s.Slug)
	}
	return fmt.Sprintf("%02d-%s.md", s.Number, s.Slug)
}

// Sections is arc42's fixed order, with the ownership split from §14.
func Sections() []Section {
	return []Section{
		{1, "Introduction and Goals", "introduction-and-goals", Human},
		{2, "Architecture Constraints", "architecture-constraints", Human},
		{3, "Context and Scope", "context-and-scope", Generated},
		{4, "Solution Strategy", "solution-strategy", Human},
		{5, "Building Block View", "building-block-view", Generated},
		{6, "Runtime View", "runtime-view", Generated},
		{7, "Deployment View", "deployment-view", Generated},
		{8, "Cross-cutting Concepts", "cross-cutting-concepts", Human},
		{9, "Architecture Decisions", "architecture-decisions", Human},
		{10, "Quality Requirements", "quality-requirements", Human},
		{11, "Risks and Technical Debt", "risks-and-technical-debt", Human},
		{12, "Glossary", "glossary", Generated},
	}
}

// Meta is what OUT-04 stamps on every generated file: enough for a reader to know which version
// of which repository produced it, and what was applied on top.
type Meta struct {
	Tool   string // archdoc build
	Commit string // the scanned repository's commit, when it has one
	Source string // the configuration file the model came from
	Rules  []string

	// Pictures is true when context.svg and container.svg are being written beside the
	// markdown. The documents then show the drawn diagram and keep the Mermaid source in a
	// collapsed block; without pictures they show Mermaid, which needs no layout engine.
	Pictures bool
}

func (m Meta) stamp() string {
	var b strings.Builder

	b.WriteString("<!-- Generated by archdoc. Do not edit: this file is overwritten in full on\n")
	b.WriteString("     every run. Corrections belong in rules.yaml, which survives regeneration.\n")
	fmt.Fprintf(&b, "     tool:   %s\n", dash(m.Tool))
	fmt.Fprintf(&b, "     commit: %s\n", dash(m.Commit))
	fmt.Fprintf(&b, "     source: %s\n", dash(m.Source))
	if len(m.Rules) > 0 {
		fmt.Fprintf(&b, "     rules:  %s\n", strings.Join(m.Rules, ", "))
	}
	b.WriteString("-->\n\n")

	return b.String()
}

// Arc42 renders every section archdoc can fill from facts. The map is keyed on file name,
// relative to the documentation directory. plan says which sections this repository has evidence
// for — see plan.go; pass Sections() for all of them.
func Arc42(m archdoc.Model, facts archdoc.FactSet, plan []Section, meta Meta) map[string]string {
	out := map[string]string{}

	for _, s := range plan {
		if s.Owner != Generated {
			continue
		}

		var b strings.Builder
		fmt.Fprintf(&b, "# %d. %s\n\n", s.Number, s.Title)
		b.WriteString(meta.stamp())

		switch s.Number {
		case 3:
			b.WriteString(contextSection(m, meta))
		case 5:
			b.WriteString(buildingBlockSection(m, meta))
		case 6:
			b.WriteString(runtimeSection(m))
		case 7:
			b.WriteString(deploymentSection(m, facts))
		case 12:
			b.WriteString(glossarySection(m))
		}

		out[s.File()] = b.String()
	}

	return out
}

func contextSection(m archdoc.Model, meta Meta) string {
	view := m.Context()

	var b strings.Builder
	b.WriteString("The system as a whole, and what surrounds it. Everything the repository declares is\n")
	b.WriteString("inside one box; everything it only references sits outside.\n\n")
	b.WriteString(figure(meta, "System context", "context.svg", Mermaid(view, false)))
	b.WriteString("\n")
	b.WriteString(elementTable(view))

	outside := 0
	for _, n := range view.Nodes {
		if n.Kind == archdoc.External {
			outside++
		}
	}
	if outside == 0 {
		b.WriteString("\nThe repository references no system it does not also declare. That is a finding\n")
		b.WriteString("about this repository, not a gap in the tool: where a system's external\n")
		b.WriteString("dependencies are configured at deploy time, the repository never names them.\n")
	}

	return b.String()
}

func buildingBlockSection(m archdoc.Model, meta Meta) string {
	view := m.Container()

	var b strings.Builder
	b.WriteString("The separately deployable pieces inside the system, and what talks to what.\n\n")
	b.WriteString(figure(meta, "Containers", "container.svg", Mermaid(view, true)))
	b.WriteString("\n")
	b.WriteString(elementTable(view))
	b.WriteString("\n")
	b.WriteString(relationshipTable(view))
	b.WriteString(networkTable(m, view))
	b.WriteString(excluded(m, view))

	return b.String()
}

// runtimeSection is generated and empty on purpose.
//
// A runtime view describes how a feature behaves *while running*. Configuration declares
// structure, never behaviour, so there is nothing here to read. Saying so — and naming the
// evidence that would be needed — is more useful than an invented sequence diagram, and it is
// what OUT-01 means by stubbing with an explicit note.
func runtimeSection(m archdoc.Model) string {
	if len(m.Flows) > 0 {
		return runtimeFromCode(m)
	}
	var b strings.Builder

	b.WriteString("**archdoc cannot fill this section from configuration.**\n\n")
	b.WriteString("A runtime view describes how a feature behaves while running — the order of calls\n")
	b.WriteString("in a scenario, what happens on failure, where work is queued. Configuration\n")
	b.WriteString("declares *structure*: what exists, and what may reach what. It says nothing about\n")
	b.WriteString("sequence, and archdoc does not guess.\n\n")
	b.WriteString("Filling it would need one of:\n\n")
	b.WriteString("- **Static analysis of application source** — call graphs within and between services\n")
	b.WriteString("- **Runtime traces** — OpenTelemetry spans, or logs correlated by request\n")
	b.WriteString("- **A person**, writing the scenarios that matter\n\n")

	if edges := len(m.Container().Edges); edges > 0 {
		fmt.Fprintf(&b, "The %d relationship(s) in section 5 are the structural skeleton such a\n", edges)
		b.WriteString("scenario would move along. They say what *can* happen, not what does.\n")
	}

	return b.String()
}

// deploymentSection is shallow by nature and useful anyway.
//
// Compose describes a single host running containers, so the mapping is one level deep — a real
// deployment view arrives with orchestrator manifests, which are out of R1 scope. What it can say
// honestly is a great deal: the image each container runs, the ports published to the host, the
// networks each sits on, and the paths the repository hands into each container.
//
// This section is also where Compose *belongs*. A compose file is a deployment descriptor, and the
// container view (§5) is the awkward projection of it; everything below was already extracted and
// then dropped on the floor because §5 must not show deployment concepts.
func deploymentSection(m archdoc.Model, facts archdoc.FactSet) string {
	var b strings.Builder

	b.WriteString("Compose describes one host running containers, so this view is one level deep.\n")
	b.WriteString("A layered deployment view needs orchestrator manifests, which are out of scope for\n")
	b.WriteString("this release. What the configuration does state is below, and all of it is declared:\n")
	b.WriteString("the image each container runs, what is published to the host, which networks each\n")
	b.WriteString("sits on, and what the repository mounts into it.\n\n")

	view := m.Container()
	svc := byName(facts)

	reachable := map[string]bool{}
	for _, e := range view.Edges {
		if from, ok := view.Node(e.From); ok && from.Kind == archdoc.Actor {
			reachable[e.To] = true
		}
	}

	b.WriteString("### Containers\n\n")
	b.WriteString("| Container | Runs | Reachable from outside | Networks | Declared at |\n|---|---|---|---|---|\n")
	for _, n := range view.Nodes {
		if !n.Kind.Container() {
			continue
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | `%s` |\n",
			n.Name, runs(svc[n.Name], n), yesNo(reachable[n.ID]),
			dash(strings.Join(n.Networks, ", ")), n.Prov)
	}

	b.WriteString(portTable(facts))
	b.WriteString(networkTable(m, view))
	b.WriteString(mountTable(facts))

	return b.String()
}

// runs is the image a container runs, or the fact that the repository builds it. A built image is
// as much a deployment fact as a pulled one, and "built here" is what tells a reader the source is
// in front of them.
func runs(s archdoc.Service, n archdoc.Node) string {
	if s.Image != "" {
		return "`" + s.Image + "`"
	}
	if n.Technology != "" {
		return "built from this repository — " + n.Technology
	}
	return "built from this repository"
}

// portTable is the host's side of the boundary: every published port, which is the only thing
// Compose says outright about what the outside world can touch.
func portTable(facts archdoc.FactSet) string {
	type row struct{ service, published, target, protocol, prov string }
	var rows []row

	for _, s := range facts.Services {
		for _, p := range s.Ports {
			protocol := p.Protocol
			if protocol == "" {
				protocol = "tcp"
			}
			rows = append(rows, row{s.Name, p.Published, fmt.Sprintf("%d", p.Target), protocol, p.Prov.String()})
		}
	}
	if len(rows) == 0 {
		return "\nNo port is published to the host. Nothing outside reaches these containers\ndirectly — whatever reaches them arrives through something this configuration does\nnot declare.\n"
	}

	sort.Slice(rows, func(i, j int) bool {
		if rows[i].service != rows[j].service {
			return rows[i].service < rows[j].service
		}
		return rows[i].published < rows[j].published
	})

	var b strings.Builder
	b.WriteString("\n### Published ports\n\n")
	b.WriteString("| Container | On the host | In the container | Protocol | Declared at |\n|---|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | `%s` |\n", r.service, r.published, r.target, r.protocol, r.prov)
	}
	return b.String()
}

// mountTable is what the repository hands to a container. It matters twice: it is how a gateway's
// routing table arrives, and it is the one place configuration says which of its own files a
// running container depends on.
func mountTable(facts archdoc.FactSet) string {
	type row struct{ service, source, target, prov string }
	var rows []row

	for _, s := range facts.Services {
		for _, mnt := range s.Mounts {
			rows = append(rows, row{s.Name, mnt.Source, mnt.Target, mnt.Prov.String()})
		}
	}
	if len(rows) == 0 {
		return ""
	}

	sort.Slice(rows, func(i, j int) bool {
		if rows[i].service != rows[j].service {
			return rows[i].service < rows[j].service
		}
		return rows[i].source < rows[j].source
	})

	var b strings.Builder
	b.WriteString("\n### What the repository mounts into containers\n\n")
	b.WriteString("| Container | From the repository | Seen inside as | Declared at |\n|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | `%s` | `%s` | `%s` |\n", r.service, r.source, r.target, r.prov)
	}
	return b.String()
}

func byName(facts archdoc.FactSet) map[string]archdoc.Service {
	out := make(map[string]archdoc.Service, len(facts.Services))
	for _, s := range facts.Services {
		out[s.Name] = s
	}
	return out
}

func glossarySection(m archdoc.Model) string {
	var b strings.Builder

	b.WriteString("Every element the model contains, with what it is and where it is declared.\n")
	b.WriteString("Terms only a person can define belong in section 8.\n\n")
	b.WriteString("| Term | Meaning | Declared at |\n|---|---|---|\n")

	nodes := append([]archdoc.Node(nil), m.Nodes...)
	sort.Slice(nodes, func(i, j int) bool { return nodes[i].Name < nodes[j].Name })

	for _, n := range nodes {
		meaning := typeName(n.Kind)
		if n.Technology != "" {
			meaning += ", " + n.Technology
		}
		if n.Description != "" {
			meaning += " — " + n.Description
		}
		fmt.Fprintf(&b, "| %s | %s | `%s` |\n", n.Name, meaning, n.Prov)
	}

	return b.String()
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

// shownFlows is how many flows the runtime view draws; the rest are in the app and the model.
const shownFlows = 8

// runtimeFromCode is the runtime view once the code was read: the flows that reach the most
// participants, each as a sequence diagram — chosen by that rule alone, stated, so the choice is
// not a judgement — and where to find the rest.
func runtimeFromCode(m archdoc.Model) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Read from the code: %d routes followed from their handler into the classes they are given,\n", len(m.Flows))
	b.WriteString("down to the tables their queries name and the calls that leave the container — each step at\n")
	b.WriteString("its line, resolved by the declared type of the field it calls through.\n\n")
	fmt.Fprintf(&b, "Below are the %d flows that reach the most participants; every route's flow is on the\n", min(shownFlows, len(m.Flows)))
	b.WriteString("Features screen of `archdoc serve` and in `.archdoc/model.json`. What a flow cannot see —\n")
	b.WriteString("failure handling, queued work picked up elsewhere, calls through functions rather than\n")
	b.WriteString("objects — is not drawn.\n")

	flows := append([]archdoc.Flow(nil), m.Flows...)
	sort.SliceStable(flows, func(i, j int) bool {
		if a, c := len(flows[i].Participants), len(flows[j].Participants); a != c {
			return a > c
		}
		return flows[i].Entry < flows[j].Entry
	})
	entries := map[string]archdoc.Entry{}
	for _, e := range m.Entries {
		entries[e.ID] = e
	}
	for i, f := range flows {
		if i == shownFlows {
			break
		}
		e := entries[f.Entry]
		fmt.Fprintf(&b, "\n### %s %s\n\n", e.Method, e.Path)
		if e.Summary != "" {
			fmt.Fprintf(&b, "%s. ", cited(e.Summary, e.SummaryProv))
		}
		fmt.Fprintf(&b, "Handled by `%s`, `%s`.\n\n", e.Handler, e.Prov)
		b.WriteString(fence(FlowMermaid(f)))
		if f.Cut {
			b.WriteString("\nCut at four calls deep or forty steps.\n")
		}
	}
	return b.String()
}

// FlowMermaid renders a flow as a Mermaid sequence diagram.
func FlowMermaid(f archdoc.Flow) string {
	var b strings.Builder
	b.WriteString("sequenceDiagram\n")
	id := map[string]string{}
	for i, p := range f.Participants {
		key := fmt.Sprintf("p%d", i)
		id[p.ID] = key
		name := p.Name
		switch p.Kind {
		case "table":
			name = p.Name + " (table)"
		case "unresolved":
			name = "address computed at run time"
		}
		fmt.Fprintf(&b, "    participant %s as %s\n", key, strings.NewReplacer(";", ",", "#", "").Replace(name))
	}
	for _, s := range f.Steps {
		fmt.Fprintf(&b, "    %s->>%s: %s\n", id[s.From], id[s.To], strings.NewReplacer(";", ",", "#", "", ":", " ").Replace(s.Call))
	}
	return b.String()
}
