package render

import (
	"fmt"
	"strings"

	"github.com/cruzambrociogl/archdoc/internal/archdoc"
)

// Document is the primary human deliverable: the diagrams, and the evidence for every element
// in them. §8 — markdown is what survives archdoc being uninstalled.
//
// Both views go in one file. They are the same model at two distances, and a reader comparing
// them should not have to open two tabs.
func Document(m archdoc.Model) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s — architecture\n\n", m.Name)
	b.WriteString("<!-- Generated by archdoc. Do not edit: this file is overwritten in full on\n")
	b.WriteString("     every run. Corrections belong in rules.yaml, which survives regeneration. -->\n\n")

	fmt.Fprintf(&b, "Derived from `%s`. Every element below cites the line that declares it.\n\n", m.Source)

	context, container := m.Context(), m.Container()

	b.WriteString("## System context\n\n")
	b.WriteString("The system as a whole, and what surrounds it. Everything the repository declares is\n")
	b.WriteString("inside one box; everything it only references sits outside.\n\n")
	b.WriteString(fence(Mermaid(context, false)))

	b.WriteString("\n## Containers\n\n")
	b.WriteString("Inside the box: the separately deployable things, and what talks to what.\n\n")
	b.WriteString(fence(Mermaid(container, true)))

	b.WriteString("\n## Evidence\n\n")
	b.WriteString(elementTable(container))
	b.WriteString("\n")
	b.WriteString(relationshipTable(container))
	b.WriteString(networkTable(m, container))

	b.WriteString(excluded(m, container))

	return b.String()
}

func fence(diagram string) string {
	return "```mermaid\n" + strings.TrimRight(diagram, "\n") + "\n```\n"
}

// figure shows a diagram: the drawn SVG when there is one, with its Mermaid source kept in a
// collapsed block for editing and diffing (§8 — "markdown embeds the SVG; the .mmd sits
// alongside"). Without a picture it falls back to Mermaid, which renders with no layout engine.
func figure(meta Meta, title, svg, mermaid string) string {
	if !meta.Pictures {
		return fence(mermaid)
	}
	return fmt.Sprintf("![%s](%s)\n\n<details>\n<summary>Diagram as text (Mermaid)</summary>\n\n%s\n</details>\n",
		title, svg, fence(mermaid))
}

// elementTable is the answer to "how do you know?" for every box on the diagram.
func elementTable(m archdoc.Model) string {
	var b strings.Builder

	b.WriteString("### Elements\n\n")
	b.WriteString("| Element | Type | Technology | Description | Evidence | Declared at |\n")
	b.WriteString("|---|---|---|---|---|---|\n")

	for _, n := range m.Nodes {
		// The technology carries its own citation: a box's name is proven by the line that
		// declares it, while what runs inside it usually came from the catalog. Showing one
		// provenance for both would credit a file with something it never said.
		tech := cited(n.Technology, n.TechProv)

		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | `%s` |\n",
			cited(n.Name, n.NameProv), typeName(n.Kind), tech, cited(n.Description, n.DescProv), n.Evidence, n.Prov)
	}

	return b.String()
}

// relationshipTable does the same for every arrow. An edge may cite more than one line: the
// same relationship declared twice, or an edge bridged through infrastructure the container
// view excludes.
func relationshipTable(m archdoc.Model) string {
	var b strings.Builder

	b.WriteString("### Relationships\n\n")

	if len(m.Edges) == 0 {
		b.WriteString("None. The configuration declares no relationship between these elements —\n")
		b.WriteString("a finding about the repository, not a gap in the tool.\n")
		return b.String()
	}

	b.WriteString("| From | To | Relationship | Technology | Declared at |\n")
	b.WriteString("|---|---|---|---|---|\n")

	for _, e := range m.Edges {
		from, _ := m.Node(e.From)
		to, _ := m.Node(e.To)

		cites := make([]string, 0, len(e.Prov))
		for _, p := range e.Prov {
			cites = append(cites, "`"+p.String()+"`")
		}

		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
			from.Name, to.Name, cited(e.Label, e.LabelProv), dash(e.Technology), strings.Join(cites, ", "))
	}

	return b.String()
}

// networkTable is the evidence for the boundaries drawn on the diagram.
//
// A network is the one reachability claim configuration makes outright: two containers sharing
// no network cannot reach each other. Compose's own `internal: true` goes further and says the
// network has no route out at all. Both are declared, so both can be cited.
func networkTable(full, view archdoc.Model) string {
	if len(full.Networks) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("\n### Networks\n\n")
	b.WriteString("| Network | Reachability | Containers | Declared at |\n")
	b.WriteString("|---|---|---|---|\n")

	for _, net := range full.Networks {
		var members []string
		for _, n := range view.Nodes {
			for _, name := range n.Networks {
				if name == net.Name {
					members = append(members, n.Name)
				}
			}
		}

		reach := "reachable from outside"
		if net.Internal {
			reach = "**no external connectivity**"
		}

		fmt.Fprintf(&b, "| %s | %s | %s | `%s` |\n",
			net.Name, reach, dash(strings.Join(members, ", ")), net.Prov)
	}

	return b.String()
}

// excluded names what the container view left out, and why.
//
// A diagram that silently drops elements is not traceable in the direction that matters most: a
// reader who knows the system will look for the gateway and needs to be told it was a decision
// rather than a miss.
func excluded(full, view archdoc.Model) string {
	shown := map[string]bool{}
	for _, n := range view.Nodes {
		shown[n.ID] = true
	}

	var missing []archdoc.Node
	for _, n := range full.Nodes {
		if !shown[n.ID] {
			missing = append(missing, n)
		}
	}

	if len(missing) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("\n### Not shown\n\n")
	b.WriteString("Infrastructure stays in the model and leaves the container view: with everything\n")
	b.WriteString("routed through a gateway, a diagram looks hub-and-spoke and hides the real\n")
	b.WriteString("couplings.\n\n")
	b.WriteString("Relationships that passed through these are reconnected to their real endpoints\n")
	b.WriteString("and cite both hops — but only where the configuration says traffic flows. A\n")
	b.WriteString("`depends_on` records start-up order, not routing, so a path made only of those is\n")
	b.WriteString("not redrawn. Where a route is missing here, it is declared in the gateway's own\n")
	b.WriteString("configuration, which archdoc does not yet read.\n\n")

	b.WriteString("| Element | Type | Declared at |\n|---|---|---|\n")
	for _, n := range missing {
		fmt.Fprintf(&b, "| %s | %s | `%s` |\n", n.Name, typeName(n.Kind), n.Prov)
	}

	return b.String()
}

func typeName(k archdoc.Kind) string {
	switch k {
	case archdoc.Actor:
		return "Person"
	case archdoc.External:
		return "External system"
	case archdoc.System:
		return "Software system"
	case archdoc.Datastore:
		return "Container (data store)"
	case archdoc.Queue:
		return "Container (queue)"
	case archdoc.Proxy:
		return "Infrastructure"
	default:
		return "Container"
	}
}

// cited renders a value with the citation for that value specifically.
//
// A box's name is proven by the line that declares it; what runs inside it usually came from a
// catalog, and what it is *for* can only have come from a person or the model. Showing one
// provenance for all three would credit a file with things it never said — and PRV-05 needs the
// reader to be able to tell interpretation from reading at a glance.
func cited(value string, prov archdoc.Provenance) string {
	if value == "" {
		return "—"
	}
	if !prov.Known() {
		return value
	}
	if prov.Origin.Interpretation() {
		// Marked, not hidden. The model's suggestions are useful and they are not facts.
		return fmt.Sprintf("*%s* <sup>`%s`</sup>", value, prov)
	}
	return fmt.Sprintf("%s <sup>`%s`</sup>", value, prov)
}

// dash keeps empty cells honest. A blank cell reads as an oversight; "—" reads as "the
// configuration does not say", which is what it means.
func dash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
