package render

import (
	"fmt"
	"strings"

	"github.com/cruzambrociogl/archdoc/internal/archdoc"
)

// Layer 3 of the output contract: a browsable, searchable, shareable site, generated from the
// committed markdown rather than instead of it.
//
// This is the answer to "share it with my team" that is not a hosted service — the one thing the
// hosted wikis have that committed markdown does not. It costs one configuration file, because the
// markdown was already written to stand on its own (§8's hard requirement). MkDocs Material renders
// Mermaid natively, so the diagrams work with no build step of ours.
//
// Opt-in, and written into the documentation directory rather than the repository root: archdoc
// does not scatter files through someone's project, and a root `mkdocs.yml` is a file a repository
// may already own.

// MkDocsFile is written beside the sections, so `mkdocs build -f docs/architecture/mkdocs.yml`
// works unmodified.
const MkDocsFile = "mkdocs.yml"

// MkDocs renders the site configuration for this document set. The navigation lists exactly the
// sections that were emitted, in arc42 order.
func MkDocs(m archdoc.Model, plan []Section) string {
	var b strings.Builder

	b.WriteString("# Generated by archdoc. Overwritten on every run with --site.\n")
	b.WriteString("# Build the site with:  mkdocs build -f docs/architecture/mkdocs.yml\n")
	b.WriteString("# Needs: pip install mkdocs-material\n\n")

	fmt.Fprintf(&b, "site_name: %s — architecture\n", yamlValue(m.Name))
	b.WriteString("docs_dir: .\n")
	b.WriteString("site_dir: ../../.archdoc/site\n")
	b.WriteString("use_directory_urls: false\n\n")

	b.WriteString("theme:\n")
	b.WriteString("  name: material\n")
	b.WriteString("  features:\n")
	b.WriteString("    - navigation.top\n")
	b.WriteString("    - search.highlight\n")
	b.WriteString("    - content.code.copy\n\n")

	b.WriteString("markdown_extensions:\n")
	b.WriteString("  - admonition\n")
	b.WriteString("  - tables\n")
	b.WriteString("  - pymdownx.details\n")
	b.WriteString("  - pymdownx.superfences:\n")
	b.WriteString("      custom_fences:\n")
	b.WriteString("        - name: mermaid\n")
	b.WriteString("          class: mermaid\n")
	b.WriteString("          format: !!python/name:pymdownx.superfences.fence_code_format\n\n")

	b.WriteString("nav:\n")
	fmt.Fprintf(&b, "  - Overview: %s\n", IndexFile)
	for _, s := range plan {
		fmt.Fprintf(&b, "  - %d. %s: %s\n", s.Number, yamlValue(s.Title), s.File())
	}
	fmt.Fprintf(&b, "  - Coverage: %s\n", CoverageFile)

	return b.String()
}

// yamlValue keeps a name that contains YAML punctuation from breaking the file. Project names come
// from other people's repositories, so they are not trusted to be plain.
func yamlValue(s string) string {
	if strings.ContainsAny(s, ":#{}[]&*!|>'\"%@`,") {
		return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
	}
	return s
}
